pipeline{
    agent { label 'verify' }
    post {
        success{
                wrap([$class: 'BuildUser']) {
                   script {
                       BUILD_USER = "${env.BUILD_USER}"
                       BUILD_USER_EMAIL = "${env.BUILD_USER_EMAIL}"
                   }
				}
            mail bcc: '',
            body: "Dear ${BUILD_USER},\n\n\tBuild secced. Please check the result.",
            from: 'devops@cixcomputing.com', replyTo: '',
            subject: "Lab loader finished",
            to: "${BUILD_USER_EMAIL}"
        }
        failure {
                wrap([$class: 'BuildUser']) {
                   script {
                       BUILD_USER = "${env.BUILD_USER}"
                       BUILD_USER_EMAIL = "${env.BUILD_USER_EMAIL}"
                   }
				}
            mail bcc: '', body: "Dear ${BUILD_USER},\n\n\tBuild failed. Please check the result.",
            cc: 'li.xu@cixtech.com',
            from: 'devops@cixcomputing.com', replyTo: '',
            subject: "Lab loader finished",
            to: "${BUILD_USER_EMAIL}"
        }
    }

    parameters {

        string(name: 'Input_Parameter', defaultValue: '-a',
        description: '')
    }
    environment {
        SH_JBN = "${JOB_BASE_NAME}"

        SH_PARA = "$params.Parameter"

        TOLIST = "cix.sw@cixtech.com anthony.tian@cixtech.com peter.zhang@cixtech.com fugang.duan@cixtech.com guoyin.chen@cixtech.com robin.wang@cixtech.com peter.chen@cixtech.com zhan.lou@cixtech.com cagent.zhang@cixtech.com"
        CCLIST = "adeline.wang@cixtech.com gang.liu@cixtech.com"
        FCCLIST = "anthony.tian@cixtech.com"
        FTOLIST = "anthony.tian@cixtech.com"
    }
    stages {
        stage('Building test') {
            steps{
                echo 'This is Firware Flashing step'
                sh '''
                echo $Input_Parameter
                #python3 -u linux_building_test/main.py
                #/home/svc.swciuser/envs/devops/bin/python3 -u main.py $Input_Parameter
                '''
            }
        }
    }
}
